# Generated by Django 6.0.6 on 2026-06-14 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
        ('saida', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saidas',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produtos', verbose_name='Produto'),
        ),
    ]
