# Generated by Django 6.0.6 on 2026-06-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
    ]
